### ISSUE TITLE
On hold temporarily

### ISSUE THREAD

**Issue by ghost** [osm2vectortiles/dem2vectorterrain#3]
With https://github.com/osm2vectortiles/osm2vectortiles/issues/387, I'm cautious about how we approach this given ongoing discussions with Mapbox and considering Mapbox Streets Style and similar styles where the terrain is specifically included are not to be used with non-Mapbox infrastructure (https://github.com/osm2vectortiles/mapbox-gl-styles/issues/3). This rules out any vector terrain compatibility with Mapbox Streets style. So any development here will need to take a different path.

See https://github.com/lukasmartinelli/naturalearthtiles for raster hillshading.

**Comment by klokan** [comment]
Raster hill shading has been rendered by @klokantech with MapTiler Pro (http://www.maptiler.com/) for the whole world already.
See: http://labs.klokantech.com/hillshading/ and contact us if you need the tiles.

**The main purpose of this repo should not be to reverse engineer existing MapBox vector tiles in any particular version, but to develop tools to create new vector tiles with hill-shading and contour lines. From this point of view - there is no reason to put the project on hold.**

For reference: The older MapBox Studio Outdoors style is released under plain BSD license without any clause excluding vector tiles: https://github.com/mapbox/mapbox-studio-outdoors.tm2 - so the name of attributes, etc. are published under an open license.
There are other Mapnik TM2 styles available under plain BSD license using contour lines and vector hill shading.

Vector tiles are also visible in an independent implementation made by ESRI, in their vector maps: http://www.arcgis.com/home/group.html?id=30de8da907d240a0bccd5ad3ff25ef4a&focus=layers

Google remains to use raster tiles for hillshading (it seems): https://www.google.com/maps/@50.4136235,16.8711877,13.84z/data=!5m1!1e4?hl=en

**Comment by lukasmartinelli** [comment]
BTW. I also think applying raster hillshades in Mapbox GL probably looks good enough for most hillshading purposes. Not sure if we want to go the route of creating hillshading vectors.

I played around with gdaldem to create hillshading for at least Switzerland (https://github.com/lukasmartinelli/swissdem). Also wanted to know more about SRTM/DEM etc. since it is really interesting area and elevation data looks so cool.

> Raster hill shading has been rendered by @klokantech with MapTiler Pro (http://www.maptiler.com/) for the whole world already.
> See: http://labs.klokantech.com/hillshading/ and contact us if you need the tiles.

Where did you get the global DEM GeoTIFF file with SRMT-1arcsec data?
Had to manually download them from Earth Explorer.
And how do you fill holes in the data? (I used `gdal_fillnodata` but one could also fill it up with SRTM-3arcsec data).

For the hillshading I now use the combined flag in gdaldem so one has transparent overlays.

```
gdaldem hillshade -s "$METERS_SCALE" -co compress=lzw -combined -compute_edges "$dem_source" "$hillshade_tif"
```

But you used a different technique right?

This look pretty good applied to vector maps (although compositing options like in Mapnik would make it look even better).

Test with Bright:

https://api.mapbox.com/styles/v1/morgenkaffee/ciqy4ji7j0003cknblo5qr9u6.html?title=true&access_token=pk.eyJ1IjoibW9yZ2Vua2FmZmVlIiwiYSI6IjIzcmN0NlkifQ.0LRTNgCc-envt9d5MzR75w#11.374972994546324/46.92808479775013/9.307123026775457/0

![bright___mapbox](https://cloud.githubusercontent.com/assets/1288339/17293413/695dfdd8-57f0-11e6-8809-14b76a250e87.png)

**Comment by ghost** [comment]
@klokan @lukasmartinelli 

Feel free to dive in, I've stepped back to look into a schema for OSM2VectorTiles. Right now I have used https://github.com/geofabrik/openstreetmap-carto-vector-tiles to get a TM2Source which I can serve with Tessera. There seems to be a minor YAML formatting issue preventing it working with OSM2VectorTiles. It uses the same tm2 as Openstreetmap-carto so it has an open license.

I also have an "import-osm2pgsql" Docker container (not pushed yet) which grabs all the shapefiles and imports into a postgis Docker container with the same build process as OSM2VectorTiles.

Finally, I have https://github.com/stirringhalo/openstreetmap-mapboxgl, which is a Mapbox GL style that isn't a 1-to-1 match for openstreetmap-carto, but it's meant to be very familiar. It needs love, specially in the amenities (icon) and labelling department (fonts) as I'm not super familiar with how to do it and what fonts we can openly use. I don't plan on fully matching openstreetmap-carto, but instead make this a very similar style, perhaps optimized for better clarity over openstreetmap-carto.

![Screenshot](https://github.com/stirringhalo/openstreetmap-mapboxgl/raw/master/screenshot2.png)

I hope to have the import-osm2pgsql container pushed, with a fix for the YAML format issue so we can use OSM2VectorTiles in the next day or so.

**Comment by romanshuvalov** [comment]
So, I've successfully added contour-importer. 

Contours are from [OpenDEM](http://www.opendem.info/download_contours.html). 

After calling `docker-compose run import-contour` all contour shapefiles downloaded from OpenDEM to /import/contour folder are imported to database. 

`import-sql` and tm2source were also modified in order to process contour tables and prepare them for exporting. 

Result:

![bright-contour-test](https://cloud.githubusercontent.com/assets/6326141/17832365/a6df2c82-6712-11e6-8947-551999c28912.png)

This is [osm2vectortiles bright style](http://osm2vectortiles.org/maps/) with couple of contour-layers added (it's just a preview, don't judge me for image quality).

There are bug visible (vertical line at 1/4 of image width), it's seam between two contour files, I have no idea why they are overlapping (probably because of converting from WGS84), but I believe it can be fixed. Also contours should be simplified/generalized for smaller zoom levels, at this moment I don't know how to do it so I keep it as is, just filter it by step value (50m and 100m while originals have 25m). 

I understand that using contour shapefiles limits us to their resolution and we can't draw hillshading but as first step I think it's fine. 

Should I submit it as a pull-request to osm2vectortiles?

**Comment by lukasmartinelli** [comment]
Awesome!!

@klokan You already had a demo with contour lines with the data from the open snow map?
Is this better quality than OpenDEM?

Otherwise I would really love a PR @romanshuvalov! ❤️ 
I think contour lines should be added to osm2vectortiles directly and not in a separate vector tile set if the tile size is still ok.

I will give you write access to osm2vectortiles so you can also work directly on a branch there and we can all contribute.

> I understand that using contour shapefiles limits us to their resolution and we can't draw hillshading but as first step I think it's fine.

I still at the moment favor hillshading with the help of traditional raster that can be mixed in as additional layer.

**Comment by romanshuvalov** [comment]
Just for your information, my objective is 3D rendering. Here is first try:

![blender-first-terrain](https://cloud.githubusercontent.com/assets/6326141/17837969/dc561d66-67d1-11e6-8169-132d69762844.png)

Screenshot is from Blender. This is PBF Vector tile converted via C program to Blender python script. 

It's not related to osm2vectortiles project, but after polygonizing contour lines I got idea. Blender gives us polygonized 3D model and theoretically it's possible to extract triangles and calculate its shading (lighter/darker) using its normal-vector data. It's already visualized by Blender 3D view window. 

I'm not going to do this, just saying. Only benefit is we don't need raster data at all. But honestly raster data can give more precise results and probably more beautiful picture.

**Comment by klokan** [comment]
The OpenSnowMap elevation data and contour shapes have higher quality then OpenDEM.

Screenshot of the same town as @romanshuvalov posted above:
![screen shot 2016-08-22 at 09 00 23](https://cloud.githubusercontent.com/assets/59284/17846120/f05073dc-6846-11e6-9aa7-8dca02dfbb3d.png)
http://www.opensnowmap.org/?zoom=15&lat=53.41508&lon=50.02776&layers=osm&marker=false

Here is a sample Shapefile for the data: https://goo.gl/nGFLR9 (click on Download in top-right)
Whole shapefile set has over 270GB!

Adjusted `import-contour` for this sample file would be amazing indeed!

**Comment by romanshuvalov** [comment]
@klokan, that 270 GB contour-shapefile is available only as one huge file or divided as OpenDEM shapefiles? Can you give a link? Also, question: is height resolution 10m only? (It's good but we can't draw 25m, only 10m-50m-100m in this case).

**Comment by klokan** [comment]
The data are divided into geo segments same as OpenDEM - see the sample for one such segment. I believe every 10m is better than every 25m ;-).

Let me know once you play with the sample and get some results, please. I would be happy to share with you the link for the complete dataset (need your Gmail/Google account - email me please). We could also help with rendering the tiles for the whole world on our cluster.

The sample is visible at http://labs.klokantech.com/hillshading/ (zoom into the Zurich area)

**Comment by romanshuvalov** [comment]
Already played. 
`
ERROR:  GetProj4StringSPI: Cannot find SRID (9805) in spatial_ref_sys
`
I've set `-s 9805:3857` for `shp2pgsql` because that sample is in [Mercator_2SP](http://www.remotesensing.org/geotiff/proj_list/mercator_2sp.html) a.k.a EPSG:9805 projection. I'm not sure how appropriately to add that projection to spatial_ref_sys table. 

By the way, where are that segments available for download?

**Comment by klokan** [comment]
There is no public download service for the individual segments available now.

The data were created in Switzerland by Yves, the author of OpenSnowMap project, who kindly shared them with us (KlokanTech & OSM2VectorTiles) for the purpose of creating the vector tiles, which we can then distribute on the Swiss academic network. Contact me to get the download link.

Details about the data are in relevant blog posts at http://blog.opensnowmap.org/
This is how they were created:
https://github.com/yvecai/DEM-scripts/blob/master/2015/merge_dem_hs_and_contour.py

Other related data sources (for reference):
https://github.com/openterrain/openterrain/wiki/Terrain-Data

BTW we should move this discussion to a different ticket.

**Comment by klokan** [comment]
Let's move the discussion to https://github.com/osm2vectortiles/osm2vectortiles/issues/408

@romanshuvalov would you please assign that ticket to you - and report what you have done there?

I am closing this ticket with the name "On hold temporarily".
